### ISSUE TITLE
Add Video Feature

### ISSUE THREAD

**Issue by Kabuki1212** [z-huang/music#1238] opened 2024-02-18 23:07 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There Are Youtube Music Videos To Watch

### Why do you want this feature?

Adding An Idea To Watch YT Music Videos

**Comment by Junagad** [comment] 2024-02-21 17:52
6java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

**Comment by Junagad** [comment] 2024-02-21 17:57
Hi

**Comment by z-huang** [comment] 2024-03-21 08:43
Duplicate of #1006

**Closed as not planned by z-huang** 2024-03-21 08:43 UTC
Labels: duplicate, enhancement

**Comment by SiddhantRakh** [comment] 2024-04-07 06:42
> Duplicate of #1006

Please update the app.
