### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by RANGARIRAIMUTOMBO** [z-huang/music#1261] opened 2024-04-09 21:12 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

make the app allow us to play and download video please 

### Why do you want this feature?

its just go to hve music and musical video in one app

**Comment by z-huang** [comment] 2024-04-17 16:33
Duplicate of #1006

**Closed as not planned by z-huang** 2024-04-17 16:33 UTC
Labels: duplicate, enhancement

**Comment by SiddhantRakh** [comment] 2024-04-17 22:08
> Duplicate of #1006

Is z-huang finally back?
