### ISSUE TITLE
animation for song covers when switching between songs

### ISSUE THREAD

**Issue by ganairm** [z-huang/music#1451] opened 2024-08-24 16:14 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

if possible, can you add an animation for the song covers to slide when switching songs?

### Why do you want this feature?

the current version doesn't have this feature, making switching songs feel too snappy and not immersive

### Additional information

i hope this is implemented in the next build ig

**Comment by z-huang** [comment] 2024-08-24 16:20
I've tried before using [HorizontalPager](https://developer.android.com/develop/ui/compose/layouts/pager#horizontalpager), but it's not stable, so it was removed.

I will try to write the component myself, but it'll take some time.

**Comment by Anonuser-code** [comment] 2024-08-24 18:44
> I've tried before using [HorizontalPager](https://developer.android.com/develop/ui/compose/layouts/pager#horizontalpager), but it's not stable, so it was removed.
> 
> I will try to write the component myself, but it'll take some time.

Zion, please check this. https://github.com/z-huang/InnerTune/issues/1436

**Comment by Nolli20** [comment] 2024-08-24 20:40
> I've tried before using [HorizontalPager](https://developer.android.com/develop/ui/compose/layouts/pager#horizontalpager), but it's not stable, so it was removed.
> 
> I will try to write the component myself, but it'll take some time.

And there aren't any other program with  other animations

**Comment by ganairm** [comment] 2024-08-25 00:45
> I've tried before using [HorizontalPager](https://developer.android.com/develop/ui/compose/layouts/pager#horizontalpager), but it's not stable, so it was removed.
> 
> I will try to write the component myself, but it'll take some time.

thank you

**Comment by z-huang** [comment] 2024-08-26 03:40
Duplicate of #1017

**Closed as not planned by z-huang** 2024-08-26 03:40 UTC
Labels: enhancement
