### ISSUE TITLE
add a innertune widget

### ISSUE THREAD

**Issue by Chronos9106** [z-huang/music#1422] opened 2024-08-21 07:13 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

add a spotify like widget 4x1 icon size preferably

### Why do you want this feature?

no other widget apps supports innertune

**Comment by z-huang** [comment] 2024-08-21 07:18
Duplicate of #101

**Closed as not planned by z-huang** 2024-08-21 07:18 UTC
Labels: enhancement
