### ISSUE TITLE
Avoid adding duplicate songs on playlist 

### ISSUE THREAD

**Issue by noegodinho** [z-huang/music#1028] opened 2023-09-03 15:44 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When I add a specific song to a playlist, if it already exists, it will be added again.
My idea would be to have a prompt asking if the user wants to add the music again. 

### Why do you want this feature?

Avoid involuntary duplication of songs in playlists.
Spotify does that for the songs of the same album. If a song appears in more than one album, then it is not prompted, which makes sense. 
![IMG_20230903_162657](https://github.com/z-huang/InnerTune/assets/5814780/f4c0ef7d-8850-40fa-b3f8-8dfa388bee7e)

### Additional information

App version: 0.5.3

**Comment by owenconnorz** [comment] 2023-09-03 16:29
Duplicate of #156

**Closed as not planned** 2023-09-04 00:54 UTC
Labels: duplicate, enhancement
