### ISSUE TITLE
YouTube Music API 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#73] opened 2022-06-01 19:55 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can you change the api to youtube music api that also grabs the meta data for home screen and faster load times for songs :)

### Why do you want this feature?

Seen other apps use this and runs perfectly but the ui is much better on your work :)

**Comment by z-huang** [comment] 2022-06-02 01:04
> Seen other apps use this and runs perfectly
Can you provide some examples?

Also, is this a duplicate of #43?

**Comment by owencz1998** [comment] 2022-06-02 16:27
Youtune uses youtubes music api and able to grab meta data for home page and its close to what I said about adding metadata to the home page but the api will get the music quicker and able to still download mate.

**Comment by airon90** [comment] 2022-06-03 06:22
> and able to still download mate

Are you sure that API policy allows music download?

**Comment by z-huang** [comment] 2022-06-03 06:36
Youtune is using the YT private API, not the official YouTube Data API.

**Comment by TGRush** [comment] 2022-06-19 01:20
due to this using NewPipe extractor, this doesnt rely on any of Google's APIs at all

**Comment by owencz1998** [comment] 2022-06-19 14:48
What would happen if it was using Google mate as I'm just getting into programming myself.

**Comment by z-huang** [comment] 2022-06-19 14:56
Currently working on this issue as said in announcement.

**Closed** 2022-08-15 11:44 UTC
Labels: enhancement
