### ISSUE TITLE
Multi-Song Selection to add them to a play list

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1094] opened 2023-09-29 18:06 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I suggest adding a "**Multi-Song Selection**" feature for playlist creation. Users can select multiple songs at once and add them to a playlist or download them for offline, and if a song is already in the playlist, indicate it with a different color to prevent duplicates. This would streamline playlist management.

Thank you.

### Why do you want this feature?

I want this feature because it takes a long time to select several songs individually when adding songs to playlists right now. Furthermore, it's unclear if a song has previously been added to a playlist, which could result in duplicates. These problems would be resolved by this feature, which would also avoid duplicate entries and improve playlist management.

**Comment by firestylefirebee** [comment] 2023-12-05 13:59
This man is actually speaking facts, it took me so long to add my liked songs to my playlist.

**Comment by z-huang** [comment] 2024-01-06 04:07
Duplicate of #695

**Closed as not planned by z-huang** 2024-01-06 04:07 UTC
Labels: enhancement
