### ISSUE TITLE
Albums And Songs

### ISSUE THREAD

**Issue by Kabuki1212** [z-huang/music#1236] opened 2024-02-18 14:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When You Open Artists Pages And Press Albums And Singles Theres A Problem

### Expected behavior

To Work Properly

### Actual behavior

Not Working

### Screenshots/Screen recordings

![Screenshot_20240218-160934_InnerTune](https://github.com/z-huang/InnerTune/assets/160406069/10408b62-2e54-459d-b1e7-81452c3508f1)

### Logs

Not Working

### InnerTune version

0.5.3

### Android version

Android 12

### Additional information

Not Working

**Comment by Junagad** [comment] 2024-02-21 17:58
java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

**Comment by ShadowWalkerM** [comment] 2024-03-01 14:59
Same not loading albums 
Andriod 11

**Comment by x421x** [comment] 2024-04-08 14:25
I also had this problem where I can't view any albums I haven't hearted yet. I managed to bypass this by restoring a backup file. If you don't have a backup ready, I guess you can try starting from scratch again. Sucks I know, but it is a solution, imperfect it may be.

**Comment by Meikkun** [comment] 2024-06-14 16:38
Same here. Android 14 on Samsung Galaxy s24.

**Comment by CarlAyoub** [comment] 2024-06-22 07:00
Same here on the Pixel 6 Pro using the latest stable release. Can anyone please point me to how I can download the latest debug version? Going to the actions tab and finding the latest debug only shows that the artifact is expired. I know it's probably very obvious but I never used a debug before.

**Comment by z-huang** [comment] 2024-08-04 07:53
Duplicate of #1295

**Closed as not planned by z-huang** 2024-08-04 07:53 UTC
Labels: bug
