### ISSUE TITLE
Playlist not opening 

### ISSUE THREAD

**Issue by Chickenshrimps** [z-huang/music#1302] opened 2024-07-06 02:36 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to featured playlist
Click on one of the playlist
It doesn't open only shows white screen

### Expected behavior

It should open 

### Actual behavior

White screen appeared failed to load data

### Screenshots/Screen recordings

![Screenshot_20240706_080552](https://github.com/z-huang/InnerTune/assets/108865702/25582b9a-424b-4c3e-a8ea-ff328d6f9ea8)

### Logs

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicResponsiveListItemRenderer.c(SourceFile:911)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:228)
	at x7.h.m(SourceFile:179)
	at x7.h$j.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### InnerTune version

0.4.4

### Android version

Android 12

**Comment by phantomwhale** [comment] 2024-07-15 00:09
The fork at https://github.com/Malopieds/InnerTune/releases has version 0.5.8 which fixed playlist / album loading issues for me.

**Comment by z-huang** [comment] 2024-08-04 07:52
Duplicate of #1295

**Closed as not planned by z-huang** 2024-08-04 07:52 UTC
Labels: bug
