### ISSUE TITLE
Show YouTube music's top trending songs.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#83] opened 2022-06-08 15:34 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Show youtube music's top trending songs on home screen.

### Why do you want this feature?

It's useful.

**Comment by z-huang** [comment] 2022-06-08 15:44
Duplicate of #43. This will be included in the future home page.

**Closed by z-huang** 2022-06-08 15:44 UTC
Labels: enhancement
