### ISSUE TITLE
Add option to play songs from storage itself

### ISSUE THREAD

**Issue by Jobatphysics** [z-huang/music#1119] opened 2023-10-18 02:57 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

We can't use this a local media player because it doesn't have feature to play song from storage please add these feature in next update

### Why do you want this feature?

Because it's just the basic need of a music player

**Comment by ThatOneUnoriginal** [comment] 2023-10-27 02:37
> Because it's just the basic need of a music player

While I do agree it'd be nice to be able to play songs from local storage (and I support the feature request), InnerTune is technically not intended as a general purpose music player, but rather a  "Material 3 _YouTube Music client_ for Android."

**Comment by z-huang** [comment] 2023-10-28 10:00
Duplicate of #3

**Closed as not planned by z-huang** 2023-10-28 10:00 UTC
Labels: duplicate, enhancement
