### ISSUE TITLE
Error 400 message 

### ISSUE THREAD

**Issue by Marco-9456** [z-huang/music#211] opened 2022-09-23 13:04 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Change language to Arabic
2. Open the app
3. You will get the following error message: <details markdown='1'><summary> Show Screenshot </summary>
![Screenshot_٢٠٢٢٠٩٢٣-١٤٤٤٢٤_Music](https://user-images.githubusercontent.com/41828058/191963856-589f733b-e926-4c3b-861c-da8ee2578cd5.jpg)
</details>

### Expected behavior

Change language or run normally at least. 

### Actual behavior

Gives ERROR message

### Music version

0.4.0

### Android version

Android 12

### Additional information

This bug only happens when changing the phone language to Arabic.

I tried English and German because i understood both and it worked as usual.

**Comment by z-huang** [comment] 2022-09-23 13:50
Duplicate of #204
Please check if your region is not supported by YouTube Music. See readme, there is a warning.

**Closed by z-huang** 2022-09-23 13:50 UTC
Labels: bug

**Comment by Marco-9456** [comment] 2022-09-23 14:10
> Duplicate of #204 Please check if your region is not supported by YouTube Music. See readme, there is a warning.

I'm in Germany which is a supported region by YT-Music,
Also this error is only showing when changing language to Arabic as i said.

**Comment by z-huang** [comment] 2022-09-23 14:37
I changed my system language to arabic, but I didn't get the error.
![Screenshot_٢٠٢٢-٠٩-٢٣-٢٢-٣٥-٠٣-٨٩٥_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/39427017/191985818-7de056a3-09b5-4224-8615-1f1f8cf70f24.jpg)

**Comment by Marco-9456** [comment] 2022-09-23 14:45
> I changed my system language to arabic, but I didn't get the error. ![Screenshot_٢٠٢٢-٠٩-٢٣-٢٢-٣٥-٠٣-٨٩٥_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/39427017/191985818-7de056a3-09b5-4224-8615-1f1f8cf70f24.jpg)

You've just changed the content language,
What i meant is happening when changing the `Phone Language`

**Comment by z-huang** [comment] 2022-09-23 15:05
I changed the system language.

**Comment by Marco-9456** [comment] 2022-09-23 15:12
> I changed the system language.

Here's a Screen record that shows what happens https://linksharing.samsungcloud.com/lrjaYaC3hoan

**Comment by z-huang** [comment] 2022-09-23 15:39
Yes, I did what you had done. So, I think it's because of IP.
