### ISSUE TITLE
Shuffling large no. Of songs (~60) stops in middle

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/music#65] opened 2022-05-30 17:37 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Have about 50-60 songs in library
2. Play any song, also press the shuffle button (intersecting lines)
3. After 10-15 songs it will simply stop, all 60 songs wont be shuffled

### Expected behavior

All the songs in library get shuffled

### Actual behavior

Only 10-15 songs play, after that playback pauses. Pressing next song button does nothing.

### Screenshots/Screen recordings

-

### Logs

-

### Music version

Latest Release

### Android version

10

### Additional information

The queue of songs have all the songs well shuffled, but it simply stops playing after about 30-40 minutes of background playback.

**Comment by airon90** [comment] 2022-05-31 09:31
@nikhilCad Are you sure that this BR isn't a duplicate of #37?

**Comment by nikhilCad** [comment] 2022-05-31 09:37
That is about changing first song in shuffle, my issue is that playback pauses and does not continue after 10-15 minutes

**Comment by airon90** [comment] 2022-05-31 09:55
> does not continue after 10-15 minutes

You wrote "3. After 10-15 songs it will simply stop, all 60 songs wont be shuffled" and I supposed that it was about shuffled playlist starting in the middle.

**Comment by nikhilCad** [comment] 2022-05-31 10:35
> > does not continue after 10-15 minutes
> 
> You wrote "3. After 10-15 songs it will simply stop, all 60 songs wont be shuffled" and I supposed that it was about shuffled playlist starting in the middle.

Typo there, its after 10-15 songs or about 45 minutes later, shuffled songs stop

**Comment by airon90** [comment] 2022-05-31 10:42
Create a log, as I can play all songs without problems

**Comment by z-huang** [comment] 2022-05-31 10:45
1. When this bug occurred, is the color of the next button clickable?
2. Is it because that the shuffled playlist goes to the end?
3. Can you use `adb logcat` to see if any error occurred?

**Comment by z-huang** [comment] 2022-09-24 09:46
I'll mark this issue as duplicate of #37.

**Closed** 2022-09-24 09:47 UTC
Labels: bug
