### ISSUE TITLE
Unable to open menu for albums and playlists

### ISSUE THREAD

**Issue by Kep0a** [z-huang/music#186] opened 2022-09-18 18:25 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search for album, tap kebab menu. (3 dots)

### Expected behavior

Bottom nav should open with options for adding to library and downloading

### Actual behavior

bottom nav does not appear

### Music version

.3.3

### Android version

Android 12 / Android 11

### Additional information

Attempted on Oneplus 6 and S22.

**Comment by owencz1998** [comment] 2022-09-18 18:33
Keep the app u have now but use this click app and it will download a debug. 

https://github.com/z-huang/music/actions/runs/3075547412

**Comment by z-huang** [comment] 2022-09-19 04:06
Duplicate of #28

**Closed by z-huang** 2022-09-19 04:06 UTC
Labels: bug
