### ISSUE TITLE
Playlist search

### ISSUE THREAD

**Issue by arbintm** [z-huang/music#74] opened 2022-06-03 01:10 UTC
Let us add the playlist searched on the playlist of the app...

**Comment by z-huang** [comment] 2022-06-03 02:50
Do you mean search for a playlist, and add the whole playlist to the library?

**Comment by airon90** [comment] 2022-06-03 06:29
If you mean that you want to search for a playlist created by you, it is a duplicate of #17

**Comment by z-huang** [comment] 2022-08-15 12:08
Close for ambiguous description.

**Closed by z-huang** 2022-08-15 12:08 UTC
