### ISSUE TITLE
New Name For Music

### ISSUE THREAD

**Issue by ActualBest** [z-huang/music#144] opened 2022-08-04 16:02 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Music is too generic - maybe MYousic because of Material You? Or MaterialMusic?

### Why do you want this feature?

The name Music is too generic and could easily be confused with similar apps

**Comment by owencz1998** [comment] 2022-08-07 06:52
Yeah he does wanna rename and redo the icon at some point but hasn't decided what he would like yet 🙂

**Comment by z-huang** [comment] 2022-08-08 06:16
Duplicate of #35.

**Closed** 2022-08-08 06:16 UTC
Labels: enhancement
