### ISSUE TITLE
Artists and playlists are not sortable

### ISSUE THREAD

**Issue by airon90** [z-huang/music#20] opened 2022-04-12 06:32 UTC
As title says

**Comment by z-huang** [comment] 2022-04-12 12:01
Added to the roadmap.

**Comment by z-huang** [comment] 2022-04-13 15:45
Duplicate of #21

**Comment by airon90** [comment] 2022-04-13 18:20
TBH #21 is just about manual sorting, this bug is about making all section sortable

**Comment by z-huang** [comment] 2022-04-13 23:22
Oops! Sorry for that. Reopen the issue.

**Closed** 2022-08-28 11:58 UTC
Labels: enhancement
