### ISSUE TITLE
Equalizer 

### ISSUE THREAD

**Issue by Sameky** [z-huang/music#164] opened 2022-08-28 12:09 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add an equalizer to the app (maybe Android s native eq, or maybe an in-app equalizer )

### Why do you want this feature?

Better sound quality

**Comment by z-huang** [comment] 2022-08-28 12:27
Duplicate of #77

**Closed by z-huang** 2022-08-28 12:27 UTC
Labels: enhancement
