### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [z-huang/music#1345] opened 2024-08-10 17:10 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)). It was until v0.5.4, but v0.5.5 is not. I build with `./gradlew assembleFossRelease`, but the resulting APKs are not identical, differences are huge. Also, the embedded commit hash (e57a56674b6e7f1318767c0b1961fb83b6ec7536) is not the one the tag points to (2c424b497aaeeb132a6c8db67acfb6c3f116e7f0) – but even building from that commit has similarly huge differences.

### Expected behavior

The app builds reproducibly.

### Actual behavior

The app does NOT build reproducibly.

### Logs

APK diff:

```diff
-------------------------------
--- /dev/fd/63  2024-08-10 19:06:38.333795221 +0200
+++ /dev/fd/62  2024-08-10 19:06:38.333795221 +0200
@@ -1,7 +1,7 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         b337ed0c
   META-INF/version-control-info.textproto
-  32-bit CRC value (hex):                         0387e74f
+  32-bit CRC value (hex):                         a9ab8605
   assets/dexopt/baseline.prof
   32-bit CRC value (hex):                         9e8ae205
   assets/dexopt/baseline.profm
@@ -239,7 +239,7 @@
   res/-7.png
   32-bit CRC value (hex):                         78e13048
   res/-9.png
-  32-bit CRC value (hex):                         e6d1d2dc
+  32-bit CRC value (hex):                         ee0d2985
   res/-I.png
   32-bit CRC value (hex):                         194a1b13
   res/-U.png
@@ -767,7 +767,7 @@
   res/RK.png
   32-bit CRC value (hex):                         74a8ed74
   res/RQ.png
-  32-bit CRC value (hex):                         595bd2bf
+  32-bit CRC value (hex):                         259c0c62
   res/RR.xml
   32-bit CRC value (hex):                         b4f824bf
   res/RW.png
@@ -879,7 +879,7 @@
   res/Wf.xml
   32-bit CRC value (hex):                         244458c1
   res/Wk.png
-  32-bit CRC value (hex):                         2bc1999b
+  32-bit CRC value (hex):                         2fd86f47
   res/Wl.png
   32-bit CRC value (hex):                         fee536fc
   res/Ws.xml
@@ -1039,7 +1039,7 @@
   res/cc.png
   32-bit CRC value (hex):                         c0025b0f
   res/ck.png
-  32-bit CRC value (hex):                         1465d9f0
+  32-bit CRC value (hex):                         745e1d98
   res/color/vector_tint_color.xml
   32-bit CRC value (hex):                         fc170232
   res/color/vector_tint_theme_color.xml
@@ -1245,7 +1245,7 @@
   res/l6.png
   32-bit CRC value (hex):                         2b24dab8
   res/l9.png
-  32-bit CRC value (hex):                         e6675998
+  32-bit CRC value (hex):                         3254bced
…
```

And some more. As mostly PNG files are affected, apart from the question what commit it was built from: did you maybe introduce some PNG crunching? That's known to be non-deterministic and would explain this behavior.

We'd appreciate if you could help making your build reproducible again. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

### InnerTune version

0.5.5

### Android version

n/a

**Comment by z-huang** [comment] 2024-08-11 03:09
I think the reason is that I built the apk before 2c424b497aaeeb132a6c8db67acfb6c3f116e7f0 was committed. PNG crunching is less suspicious because I didn't add anything respecting to it from 0.5.4 to 0.5.5.

How can I update the apk for you? Is directly replacing the apk file in the releases okay?

**Comment by IzzySoft** [comment] 2024-08-11 10:27
> I think the reason is that I built the apk before https://github.com/z-huang/InnerTune/commit/2c424b497aaeeb132a6c8db67acfb6c3f116e7f0 was committed.

Ah, built from a "dirty tree" – yes, that would explain it as well (especially if related parts were touched then).

> Is directly replacing the apk file in the releases okay?

No, it's not a good practice to replace things that were already distributed (whoever installed that APK already would not receive update information anyway – and showing that version as RB then would be ambiguous: while for the more tech-savvy the relevant details could be found, it would not be that obvious *which* of the APKs was meant). I'd suggest we stay transparent here: I'd commit the "RB fail" on the next run (last time I just reset the run pretending it was not yet tested), and have future releases RB again then.

If you want to be sure it was the "dirty tree", you can attach an APK to a comment here (just *rename* it to `*.zip` as Github doesn't allow `*.apk`, so I can use the URL directly; would you put it inside another ZIP it would make things unnecessarily harder for me as I'd then need to unpack and host the APK on some other web server :wink:) and name the commit I should compare against; I'd then perform a test run on it.

Alternatively, you could also make a "maintenance release" (0.5.6 or even just 0.5.5.1) – and the 3rd variant would be doing that after we've checked :wink:

**Comment by z-huang** [comment] 2024-08-12 03:42
Here you are: [InnerTune_v0.5.5_foss.zip](https://github.com/user-attachments/files/16577164/InnerTune_v0.5.5_foss.zip). It's just an apk file (renamed to .zip). Please check for me, thanks.

I will skip this version because a new version is going to be released soon.

**Comment by IzzySoft** [comment] 2024-08-12 07:19
That one has huge differences (compared to the one built from the tag). Did you build it from a different commit – and if so, which one?

**Comment by z-huang** [comment] 2024-08-12 08:33
I built it on tag v0.5.5. Here are some reasons I think:

- Didn't clean the project before building the apk
- v0.5.5 is on dev branch, not master

Anyway, I'll clean the project and build it again.

**Comment by z-huang** [comment] 2024-08-12 13:35
[app-foss-release.zip](https://github.com/user-attachments/files/16582650/app-foss-release.zip)

**Comment by IzzySoft** [comment] 2024-08-12 15:55
Nope, same, sorry:

```diff
-------------------------------
--- /dev/fd/63  2024-08-12 17:54:42.375604271 +0200
+++ /dev/fd/62  2024-08-12 17:54:42.375604271 +0200
@@ -239,7 +239,7 @@
   res/-7.png
   32-bit CRC value (hex):                         78e13048
   res/-9.png
-  32-bit CRC value (hex):                         e6d1d2dc
+  32-bit CRC value (hex):                         ee0d2985
   res/-I.png
   32-bit CRC value (hex):                         194a1b13
   res/-U.png
@@ -767,7 +767,7 @@
   res/RK.png
   32-bit CRC value (hex):                         74a8ed74
   res/RQ.png
-  32-bit CRC value (hex):                         595bd2bf
+  32-bit CRC value (hex):                         259c0c62
   res/RR.xml
   32-bit CRC value (hex):                         b4f824bf
   res/RW.png
@@ -879,7 +879,7 @@
   res/Wf.xml
   32-bit CRC value (hex):                         244458c1
   res/Wk.png
-  32-bit CRC value (hex):                         2bc1999b
+  32-bit CRC value (hex):                         2fd86f47
   res/Wl.png
   32-bit CRC value (hex):                         fee536fc
   res/Ws.xml
@@ -1039,7 +1039,7 @@
   res/cc.png
   32-bit CRC value (hex):                         c0025b0f
   res/ck.png
-  32-bit CRC value (hex):                         1465d9f0
+  32-bit CRC value (hex):                         745e1d98
...
```

**Comment by z-huang** [comment] 2024-08-12 16:30
Is zulu jdk okay to use?
As for PNG crunching, Android doc says that this is disabled by default.
Besides these possibilities, I have no idea why reproducible build stops working, since I'm following the past process to generate apks.
As a reasonable guess, 0.5.6 won't pass the reproducible build. 🥲

**Comment by licaon-kter** [comment] 2024-08-12 16:31
> Is zulu jdk okay to use?

Only OpenJDK from Debian, for F-Droid

You think a different build, like from Zulu, has extra stuff that helps?

**Comment by linsui** [comment] 2024-08-12 16:35
JDK is not related to images. Maybe it's due to https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/VectorDrawables#generateddensities.

**Comment by IzzySoft** [comment] 2024-08-12 16:45
Yupp, with VerctorDrawables we had this in at least one other app as well. Andd it is indeed just the PNG files in `res/` that differ.

**Comment by z-huang** [comment] 2024-08-12 17:01
> You think a different build, like from Zulu, has extra stuff that helps?

I'm using zulu from the very beginning of this app. I think jdk isn't the problem, but I still asked just to be safe.

> And it is indeed just the PNG files in res/ that differ.

I found many png files in these directories:

- ./app/build/intermediates/merged-not-compiled-resources/foss/release/drawable
- ./app/build/intermediates/merged-not-compiled-resources/foss/release/drawable-xhdpi-v4
- ./app/build/intermediates/merged-not-compiled-resources/foss/release/drawable-xxhdpi-v4
- ./app/build/intermediates/merged-not-compiled-resources/foss/release/drawable-xxxhdpi-v4
- ...

Maybe it's these pngs that are causing the differences?

> If you're using [Android Gradle plugin 3.0.0](https://developer.android.com/studio/releases/gradle-plugin#3-0-0) or higher, PNG crunching is disabled by default for the "debug" build type.

Oops, looks like I can disable `crunchPngs` and try again.

**Comment by IzzySoft** [comment] 2024-08-12 17:20
> Oops, looks like I can disable `crunchPngs` and try again.

:man_facepalming: I've mentioned that with my initial comment, as that's the most logical candidate. If you can build an APK without crunching, then name the commit and provide the APK (e.g. attach it here **renamed** to `*.zip`, don't put it inside another ZIP) I can give it a test run.

**Comment by z-huang** [comment] 2024-08-13 00:57
Sorry, my bad. Here you are:
[app-foss-release-0.5.6.zip](https://github.com/user-attachments/files/16593133/app-foss-release-0.5.6.zip)
[app-foss-release-0.5.5.zip](https://github.com/user-attachments/files/16593162/app-foss-release-0.5.5.zip)

**Comment by IzzySoft** [comment] 2024-08-13 08:20
Which would be the corresponding commits? Right at their tags? I mean, you'd have had to change some code to turn of crunching. So these APKs were built from that changed code – but i#d build from unchanged code. I somehow doubt that would lead to RBs. Unless it's just a line to modify somewhere and I'd include that with the recipe here as well.

Tried nevertheless with 0.5.6 – as expected, not RB for the same reason, as most likely crunching is still active on my end. OK, compared with your `build.gradle.kts` and added a

```yaml
    - sed -r '/isShrinkResources = true/a\            isCrunchPngs = false' -i app/build.gradle.kts
```

to my build recipe, let's see how that turns out… <s>Unfortunately not RB either, still differences in even more PNGs…</s> Strike that, need to run again, forgot to put in your updated APK :see_no_evil: 

OK, success :partying_face: – so that's it, as initially suspected! Hereby confirmed for v0.5.6.

**Comment by z-huang** [comment] 2024-08-14 01:23
Thanks for your help! Can I make a release at b7c72f0a so that it can be published to IzzyOnDroid and F-Droid?

**Comment by linsui** [comment] 2024-08-14 02:57
Yes, please. :)

**Comment by IzzySoft** [comment] 2024-08-14 07:36
Sure! But please make it a new release (e.g. v0.5.7), not something replacing v0.5.6 which was already distributed :wink:

**Closed as completed** 2024-08-20 10:27 UTC
Labels: bug

**Comment by z-huang** [comment] 2024-08-21 01:42
@IzzySoft May I ask when will the new version be published to your repo? It has been 5 days and I remember that it doesn't take too long in the past. Thanks.

**Comment by IzzySoft** [comment] 2024-08-21 07:37
Ah, apologies! Updates were demoted to monthly checks due to #935 (forgot to restore it to daily back when that was solved it seems) – manually triggered an update now:

```
...
com.zionhuang.music: 0.5.3/0.5.8, https://github.com/z-huang/InnerTune/releases: https://github.com/z-huang/InnerTune/releases/download/v0.5.8/InnerTune_v0.5.8_foss.apk
- Grabbing update for com.zionhuang.music: OK
- Checking 'repo/com.zionhuang.music_24.apk' for libraries and malware …
- Checking the app's AndroidManifest.xml …
! repo/com.zionhuang.music_24.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
...
```

To avoid that `DEPENDENCY_INFO_BLOCK`, a minor addition to your `build.gradle` would be appreciated:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Library list now looks fine btw, so I've set it back to daily:

```
$ iod shell lsmods com.zionhuang.music
* Android Support v4 (Development Framework) 
* Jetpack Compose (Development Framework) 
* Androidx Core (Utility) 
* DataStore (Development Aid) 
* Android Emoji2 Compat (UI Component) 
* Androidx Graphics (Utility) 
* Lifecycle (Utility) 
* AndroidX Media (Utility) 
* ProfileInstaller (Utility) 
* Room (Utility) 
* Startup (Utility) 
* Android Jetpack VersionedParcelable (Utility) 
* Coil (Utility) 
* OkHttp (Utility) 
* Ktor (Development Framework) 
* Kotlin serialization (Utility) 
* Simple Logging Facade for Java (Utility) 
```

**Comment by z-huang** [comment] 2024-08-21 07:51
Thanks! I added the code in 2f5576cc3767f516d8456850d5c8134887523f31. Will `DEPENDENCY_INFO_BLOCK` prevent this version from being accepted?

**Comment by IzzySoft** [comment] 2024-08-21 08:15
Thanks! And no, it's currently still on "notice/warning" level – so we mention it when already talking with app authors (like here) to have as many of them fixed already (less work later then), but don't even raise issues "just because of it" **yet**. That will most likely happen later, though, so it's good to be prepared; our team is small, so we try to focus on "one major topic at a time" (which currently is still reproducible builds), next to the "daily business" :wink:
