### ISSUE TITLE
Player seek bar inaccurate (at last position)

### ISSUE THREAD

**Issue by pritkr** [z-huang/music#103] opened 2022-06-11 10:33 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song in affected device.

### Expected behavior

Player seek bar should be at position at which the song is being played and once paused pause/play button should change to it and pause the song

### Actual behavior

Player seek bar is inaccurate and only at last position but when it is paused it gets back to its current position but when it is played again it is at last position
Also play pause button doesn't seem to change when pressed

### Screenshots/Screen recordings

![Screenshot_2022-06-11-15-53-57-676_com zionhuang music](https://user-images.githubusercontent.com/81620727/173183946-1af05bcd-c47e-4932-9b1d-5959458ab93b.jpg)
![Screenshot_2022-06-11-15-54-48-402_com zionhuang music](https://user-images.githubusercontent.com/81620727/173183955-3d691f98-8829-4c00-b8ba-3b77780257de.jpg)

### Music version

0.3.1

### Android version

Android 8.1 miui

### Additional information

This bug is not on all devices. It works perfectly on other device with android 12

**Comment by z-huang** [comment] 2022-06-11 11:29
Do you disable animation in your phone?

**Comment by pritkr** [comment] 2022-06-11 12:20
Yes I disable animations and this app is not respecting it but that's not a major issue

**Comment by z-huang** [comment] 2022-06-11 12:26
Then it's a duplicate of #53. But it still needs to be fixed.

**Comment by JPGuillemin** [comment] 2022-10-01 07:48
I confirm this bug. I consider it as critical bug, since the ability to seek is a major feature for a player.

**Comment by z-huang** [comment] 2022-10-01 09:17
Okay. I'm currently working on player redesign. This will be fixed, too.

**Comment by JPGuillemin** [comment] 2022-10-01 10:47
Cool :)

**Comment by JPGuillemin** [comment] 2022-10-05 18:53
Any time soon ?

**Closed** 2022-10-06 14:24 UTC
Labels: bug
