### ISSUE TITLE
Use system equalizer.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#87] opened 2022-06-09 07:38 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

add option to use system equalizer.

### Why do you want this feature?

It's necessary

**Comment by z-huang** [comment] 2022-06-09 07:55
Duplicate of #77.

**Closed by z-huang** 2022-06-09 07:55 UTC
Labels: enhancement
