### ISSUE TITLE
Ability to import a playlist cover from your gallery 

### ISSUE THREAD

**Issue by ChkChkBoom** [z-huang/music#1522] opened 2024-09-01 17:00 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The ability to change the cover of your playlists by using an image from your local gallery. This could be done by clicking the edit button and clicking on 'Import Playlist Cover' or another similar promt
![IMG_20240901_195249](https://github.com/user-attachments/assets/6e79300f-fc81-4fff-bd8d-8c8fc6584d93)

### Why do you want this feature?

It makes it easier to locate playlists as each would have it's own unique, distinctive cover. Images are quicker to recognise than text, especially in cases where playlists have similar names.

Also, it makes it makes your playlist library more attractive as you can have them themed to match the genre/ artists in them, colour-coded e.t.c

**Comment by z-huang** [comment] 2024-09-02 00:32
Duplicate of #1114.

**Closed as not planned by z-huang** 2024-09-02 00:32 UTC
Labels: enhancement
