### ISSUE TITLE
Unable to load songs and playlists 

### ISSUE THREAD

**Issue by Gowth0127** [z-huang/music#1305] opened 2024-07-07 15:43 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open innertune
2. Navigate to songs page
3. Search for any movie
4. Here you can find the bug (empty list, nothing was showing)

### Expected behavior

Songs should be viewable 

### Actual behavior

Showing blank screen or following error

java.util.NoSuchElementException: List is empty.
	at ra.q.H0(Unknown Source:21)
	at x7.h.a(SourceFile:235)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### Logs

No logs were recorded 

### InnerTune version

0.4.4

### Android version

12

**Comment by phantomwhale** [comment] 2024-07-15 00:07
Latest version is 0.5.3 in this repo.

Mind you, as I've just discovered, the fork at https://github.com/Malopieds/InnerTune/releases has version 0.5.8 which fixed playlist / album loading issues for me.

So I've moved over to that fork (which has active development; kudos to @Malopieds) and away from this release (which appears to be no longer working now; but kudos to @z-huang for all his work underpinning the new fork)

**Comment by macharia22** [comment] 2024-07-15 02:35
Kindly help me unsubscribe from this thread. I have tried so yard but
messages keep appearing

**Comment by RSoulwin** [comment] 2024-07-15 03:49
@macharia i think you are watching this repo, Just Unwatch this repo press that eye icon again on this repository's main page.

**Comment by z-huang** [comment] 2024-08-04 07:56
Duplicate of #1295

**Closed as not planned by z-huang** 2024-08-04 07:56 UTC
Labels: bug

**Comment by Godhizuki249** [comment] 2024-10-27 13:30
Oque eu vou fazer com isso, pra enfiar na minha bunda?
