### ISSUE TITLE
Song Already Exist in Playlist Pop-up

### ISSUE THREAD

**Issue by guleriaakshit** [z-huang/music#1086] opened 2023-09-22 04:44 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hi there,

I hope you are doing well and thanks for all the blood and sweat you been putting in this project. So, today I spotted that you can add a song to the same playlist over and over and it shouldn't be like that. I other playlist makers on InnerTune will really appreciate if you can fix it, thanks. 🙂

And once again that for making InnerTube, I hope this project keeps on going. 💖

Warm regards, 
Akshit

### Why do you want this feature?

This feature will benefit playlist creation experience. 👻

**Comment by z-huang** [comment] 2023-09-22 13:37
Thanks for your support :)
Duplicate of #156.

**Closed as not planned by z-huang** 2023-09-22 13:37 UTC
Labels: duplicate, enhancement
