### ISSUE TITLE
YouTube music Sync

### ISSUE THREAD

**Issue by Ledenav** [z-huang/music#1149] opened 2023-11-18 08:21 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [x] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Liked songs and playlists should sync with YouTube music.

### Why do you want this feature?

Accessing my innerTune lists from YouTube Music via computer

**Comment by z-huang** [comment] 2024-01-07 13:05
Duplicate of #990

**Closed as not planned by z-huang** 2024-01-07 13:05 UTC
Labels: duplicate, enhancement
