### ISSUE TITLE
Multiple pages are unable to load

### ISSUE THREAD

**Issue by SamIsNotStupid** [z-huang/music#297] opened 2022-10-14 04:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Simply go to the home page and-
![Screenshot_20221014-000712_Music](https://user-images.githubusercontent.com/89709731/195760287-c6a7e327-43d2-4802-b965-b2d56e8c4cb0.jpg)
It is already unable to render this page. This bug occurs in many places, the most annoying being off of the artist's page- Clicking the button for all albums immediately gives an error.

### Expected behavior

It should continue to scroll down and show you more songs, and should show you all albums.

### Actual behavior

It errors out and gives this error code-

java.lang.NullPointerException
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:25)
	at z6.g.b(SourceFile:4)
	at z6.g$c.t(Unknown Source:12)
	at u9.a.n(Unknown Source:8)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at ka.p0.run(Unknown Source:86)
	at pa.j.run(Unknown Source:12)
	at qa.j.run(Unknown Source:2)
	at qa.a$a.run(SourceFile:9)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/89709731/195760657-b3dcc85e-9b24-4d9c-842d-8eb48b3d345d.mp4

### Logs

java.lang.NullPointerException
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:25)
	at z6.g.a(SourceFile:8)
	at z6.g$b.t(Unknown Source:12)
	at u9.a.n(Unknown Source:8)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at ka.p0.run(Unknown Source:86)
	at pa.j.run(Unknown Source:12)
	at qa.j.run(Unknown Source:2)
	at qa.a$a.run(SourceFile:9)

### Music version

0.4.1

### Android version

Android 12, oneUI 4.1

### Additional information

Great job on the app, love it!

**Comment by z-huang** [comment] 2022-10-14 04:22
Duplicate of #290

**Closed** 2022-10-14 04:22 UTC
Labels: bug
