### ISSUE TITLE
Bring back selecting multiple songs

### ISSUE THREAD

**Issue by SherbetS44105** [z-huang/music#1213] opened 2024-01-18 18:01 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1 long press a song

### Expected behavior

Song selected and able to select more

### Actual behavior

Nothing happens

### Logs

N/A

### InnerTune version

0.5.3

### Android version

Android 13

### Additional information

Please bring this feature back! I've been a user of this app since before 5.0 and the removal of the feature to select multiple songs has severely crippled my ability to use this app. My library has 2000+ songs making tasks like downloading songs or creating playlists a herculean feat.

**Comment by owenconnorz** [comment] 2024-01-19 12:55
This is because it wasn't made available in compose I requested this already a while back so hopefully it's available now.

**Comment by z-huang** [comment] 2024-01-21 06:33
Duplicate of #695

**Closed as not planned by z-huang** 2024-01-21 06:33 UTC
Labels: bug, duplicate
