### ISSUE TITLE
The artist's singles are infinitely charged

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1121] opened 2023-10-19 23:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When I search for an artist, for example "fahjah", and I click on the singles, they don't load, here are the steps and a screen recording I made as an example of the issue.

1) search artist "fahjah"
2) Enter the artist
3) view singles
4) infinite charge

### Expected behavior

Correctly load the singles

### Actual behavior

Loading singles waiting

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/148503050/dd5fc3cb-9386-4aab-a8ba-0c004a054787

### Logs

I haven't logs at this time

### InnerTune version

0.5.3

### Android version

Android 12

**Comment by SiddhantRakh** [comment] 2023-10-25 07:35
Same here.

**Comment by z-huang** [comment] 2023-10-28 00:31
Duplicate of #1048

**Closed as not planned by z-huang** 2023-10-28 00:31 UTC
Labels: bug
