### ISSUE TITLE
App constantly crash on new release

### ISSUE THREAD

**Issue by smarttommyau** [z-huang/music#165] opened 2022-08-28 13:12 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Simpily start the app, the app crash and close itself within a second.

You can stop it from crash if you instantly get into the setting before it crash, by double tap the right top on the top.

### Expected behavior

Should not crash

### Actual behavior

it crash

### Logs

08-28 21:09:31.430  3573  3643 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
08-28 21:09:31.430  3573  3643 E AndroidRuntime: Process: com.zionhuang.music, PID: 3573
08-28 21:09:31.430  3573  3643 E AndroidRuntime: java.lang.NullPointerException
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        at com.zionhuang.music.utils.DownloadProgressMapLiveData$onActive$1$1.invoke(DownloadProgressMapLiveData.kt:25)
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        at com.zionhuang.music.utils.DownloadProgressMapLiveData$onActive$1.invokeSuspend(DownloadProgressMapLiveData.kt:16)
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
08-28 21:09:31.430  3573  3643 E AndroidRuntime:        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@12aed69, Dispatchers.IO]
08-28 21:09:31.437  1465  5586 W ActivityTaskManager: finishTopCrashedActivityLocked Force finishing activity com.zionhuang.music/.ui.activities.MainActivity

### Music version

0.3.3

### Android version

Harmony os 2.0.1.241/Android 11

**Comment by z-huang** [comment] 2022-08-28 13:33
Does clearing app data help?

**Comment by smarttommyau** [comment] 2022-08-28 14:17
Yes it does.

**Comment by owencz1998** [comment] 2022-08-28 14:19
This is where backup and restore would come in hand 😂happened to me aswell 🙂

**Comment by z-huang** [comment] 2022-08-28 14:28
So, duplicate of #145

I will implement backup and restore after the database structure becomes stable.

**Closed by z-huang** 2022-08-28 14:28 UTC
Labels: bug

**Comment by owencz1998** [comment] 2022-08-28 14:32
Yeah I know its already a feature request I was just saying that's a reason it would be handy to have as you never know when something will go wrong :) and awsome thanks mate 👍
