### ISSUE TITLE
Bring back the directory with all downloaded songs

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1035] opened 2023-09-06 13:01 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To simply have the folder that would accessible in ~/Android/Data/io.zionhuang.InnerTune with all the downloaded music.

### Why do you want this feature?

When I previously used InnerTune, it had a downloads folder I could access through my desktop, which is useful for when I'm backing up my mobile device, or migrating to a new one. 

(I know that this would most likely not return due to the risks that people sailing the high seas would use this application to illegally obtain music from YouTube Music.)

**Comment by z-huang** [comment] 2023-09-06 15:27
Duplicate of #813

**Closed as not planned by z-huang** 2023-09-06 15:27 UTC
Labels: duplicate, enhancement
