### ISSUE TITLE
android tv support? 

### ISSUE THREAD

**Issue by t3hee** [z-huang/music#1555] opened 2024-09-05 00:52 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

i would like to use this applicatiom on android tv 

### Why do you want this feature?

multitasking with this app

**Comment by Roxo7777** [comment] 2024-09-05 15:49
I don't know if it's easy for Kotlin to be ported to manual support for Android TV, anyway, it shouldn't be the goal in the first few upcoming versions of the app. For now, try to see what auto support you have.

**Comment by z-huang** [comment] 2024-09-06 01:59
Duplicate of #1477.

**Closed as not planned by z-huang** 2024-09-06 01:59 UTC
Labels: enhancement
