### ISSUE TITLE
Not able to use the app properly,  error code 400

### ISSUE THREAD

**Issue by smarttommyau** [z-huang/music#204] opened 2022-09-21 13:55 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Just open the app, the home page and search page only show a json format error message. 

### Expected behavior

It should show song and search result. 

### Actual behavior

it only show an error message, embed on below. 

### Screenshots/Screen recordings

![Screenshot_20220921_215123_com zionhuang music](https://user-images.githubusercontent.com/75346987/191523336-47985f3e-1d65-4845-aa93-351e9f7463f4.jpg)

### Music version

0.4.0

### Android version

Harmony os 2 (AOSP Android 11)

**Comment by z-huang** [comment] 2022-09-21 14:51
Duplicate of #190

**Closed** 2022-09-21 14:51 UTC
Labels: bug

**Comment by smarttommyau** [comment] 2022-09-21 15:51
umm but i am in Hong Kong not China😥. I think for these situation, the region and language should depends on the ip location but not system location.Or maybe a simply setup screen to select language and region. Or just write an FAQ for this. This should improve the user experience. Thank you

**Comment by z-huang** [comment] 2022-09-21 15:56
Is YT Music supported in Hong Kong? If so, and your system settings has region in Hong Kong, you should not be able to see the error.

**Comment by smarttommyau** [comment] 2022-09-21 16:22
Yes Hong Kong is supported. I can get to YT Music site without open any proxy or vpn. But I set the system region to China, as it will support more features of my phone, but the app auto follow the region of my phone not my location, so if I change the inapp region to HK and inapp language to中文（香港）the app work normal. And it is kind of confusing as the language is also needed to change, as the app don't work when only changing the content country.
