### ISSUE TITLE
"Explore" and "songs" tab non clickable.

### ISSUE THREAD

**Issue by max5354** [z-huang/music#95] opened 2022-06-09 14:41 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Sometimes "Explore" and "Songs" Tab is Non clickable no matter how many times we press on it. It just showing animation but not working. We need to exit and reopen app for work them properly. Please fix this.

### Expected behavior

be clickable button.

### Actual behavior

Not clickable button.

### Music version

0.3.1

### Android version

Android 10

**Comment by z-huang** [comment] 2022-06-09 14:50
> It just showing animation but not working.

What animation is it showing?

**Comment by max5354** [comment] 2022-06-10 02:56
> Is this a duplicate of #12?

No. It's different bug. I tried everything like restart phone and reinstall app. But that bug is still.

**Comment by z-huang** [comment] 2022-06-10 03:32
Can you make a screen recording?

**Comment by max5354** [comment] 2022-06-10 04:05
Look. This type of bug happens. Not clickable "songs" button.

**Comment by max5354** [comment] 2022-06-10 04:07
https://user-images.githubusercontent.com/90886938/172988413-25e1133f-9d08-457a-9757-18186242d9cb.mp4

**Comment by z-huang** [comment] 2022-06-10 04:47
OK, it's a duplicate of #12.

**Closed** 2022-06-10 04:47 UTC
Labels: bug
