### ISSUE TITLE
App icon not loaded 

### ISSUE THREAD

**Issue by anujithpp** [z-huang/music#464] opened 2022-12-05 17:04 UTC
![IMG_20221205_223329.jpg](https://user-images.githubusercontent.com/106502495/205697912-5c27dda4-3d36-4eae-abfc-e56ee4749259.jpg)

**Comment by z-huang** [comment] 2022-12-05 23:31
Duplicate of #230

**Closed as not planned by z-huang** 2022-12-05 23:31 UTC
Labels: duplicate

**Comment by ShareASmile** [comment] 2022-12-06 15:00
Try steps given in this comment if that helps:
https://github.com/z-huang/InnerTune/issues/230#issuecomment-1327660351
