### ISSUE TITLE
Can't load home page

### ISSUE THREAD

**Issue by CuongBa956** [z-huang/music#311] opened 2022-10-16 05:49 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to home page

### Expected behavior

an error message appears

### Actual behavior

I can't load anything on the home page other than the radio quick select and suggestions below.

### Screenshots/Screen recordings

![Screenshot_20221016-124055](https://user-images.githubusercontent.com/89731755/196020057-4dc1b5dd-6717-4929-abb7-b91bbb04d4c7.png)
![Screenshot_20221016-124050](https://user-images.githubusercontent.com/89731755/196020062-7c337f51-58c3-4136-bba4-ef5f436db066.png)

### Music version

0.4.1

### Android version

Android 12 

### Additional information

java.lang.NullPointerException
	at com.zionhuang.innertube.models.response.BrowseR sponse.a(SourceFile:25)
	at z6.g.b(SourceFile:4)
	at z6.g$c.t(Unknown Source:12)
	at u9.a.n(Unknown Source:8)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at ka.p0.run(Unknown Source:86)
	at pa.j.run(Unknown Source:12)
	at qa.j.run(Unknown Source:2)
	at qa.a$a.run(SourceFile:9)

**Comment by z-huang** [comment] 2022-10-16 06:40
Duplicate of #290

**Closed** 2022-10-16 06:40 UTC
Labels: bug, duplicate
