### ISSUE TITLE
Add squiggly progress bar

### ISSUE THREAD

**Issue by JCionx** [z-huang/music#1171] opened 2023-12-16 20:41 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add the new android progress bar to the app, just like on this image:
![image](https://github.com/z-huang/InnerTune/assets/92257741/d62f2909-b186-4471-b9db-f4d1588f6f13)

### Why do you want this feature?

It's a design improve, and a step forward to becoming more concise with material design.

### Additional information

![image](https://github.com/z-huang/InnerTune/assets/92257741/13c419cd-e7d4-4e6e-bd61-c398974f6cb4)

**Comment by Malopieds** [comment] 2023-12-17 13:53
If you're talking about the notification bar, it is Android wise, meaning it's implemented since android 14 I think, and it's not related to the app itself. If you want it in the player then I don't think it's a good idea, because messy.

**Comment by JCionx** [comment] 2023-12-17 13:57
> If you're talking about the notification bar, it is Android wise, meaning it's implemented since android 14 I think, and it's not related to the app itself. If you want it in the player then I don't think it's a good idea, because messy.

I was talking about adding it to the player. I understand it might be complicated to implement, but [Vanilla Music Player](https://github.com/vanilla-music/vanilla) has that feature.

**Comment by z-huang** [comment] 2024-01-10 09:02
Duplicate of #1099

**Closed as not planned by z-huang** 2024-01-10 09:02 UTC
Labels: enhancement
