### ISSUE TITLE
Fetching too many songs leads to a crash

### ISSUE THREAD

**Issue by airon90** [z-huang/music#201] opened 2022-09-21 08:32 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Have a lot of songs (I have 3600+ songs, you can have 150 songs) on Music v0.3.3 or lower
2. Upgrade to v0.4
3. Songs don't have any cover. Select (manually!) all songs and select Refetch
4. App crashes

### Expected behavior

Fetching new data

### Actual behavior

Crash

### Logs

```--------- beginning of main
09-21 10:27:43.706 13962 13962 E zionhuang.musi: Not starting debugger since process cannot load the jdwp agent.
09-21 10:27:43.707 13962 13962 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-21 10:27:43.715 13962 13962 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10377; state: ENABLED
09-21 10:27:43.721 13962 13981 D AppScoutStateMachine: 13962-ScoutStateMachinecreated
09-21 10:27:43.730 13962 13962 V GraphicsEnvironment: ANGLE Developer option for 'com.zionhuang.music' set to: 'default'
09-21 10:27:43.730 13962 13962 V GraphicsEnvironment: Updatable production driver is not supported on the device.
--------- beginning of system
09-21 10:27:43.731 13962 13962 I ForceDarkHelperStubImpl: initialize for com.zionhuang.music , ForceDarkOrigin
09-21 10:27:43.732 13962 13962 D OpenGLRenderer: JNI_OnLoad success
09-21 10:27:43.732 13962 13962 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
09-21 10:27:43.732 13962 13962 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 10:27:43.733 13962 13962 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-21 10:27:43.738 13962 13962 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
09-21 10:27:43.749 13962 13984 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10377; state: ENABLED
09-21 10:27:43.760 13962 13962 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
09-21 10:27:43.782 13962 13962 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 10:27:43.819 13962 13962 W DataBinding: Setting the fragment as the LifecycleOwner might cause memory leaks because views lives shorter than the Fragment. Consider using Fragment's view lifecycle
09-21 10:27:43.819 13962 13997 E QXPerf  : Couldn't load BLASTBufferQueue Class
09-21 10:27:43.819 13962 13997 E QXPerf  : Couldn't find UndequeuedBufferCount functions
09-21 10:27:43.830 13962 13962 D DecorView[]: getWindowModeFromSystem  windowmode is 1
09-21 10:27:43.843 13962 13962 I ExoPlayerImpl: Init 6a445e8 [ExoPlayerLib/2.18.1] [vili, 2107113SG, Xiaomi, 31]
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: QUALCOMM build                   : 4a124bc, I55aa49cfcc
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: Build Date                       : 06/03/21
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.08
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: Local Branch                     : gfx-a6x.lnx.2.0.1
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: Remote Branch                    : 
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: Remote Branch                    : 
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: Reconstruct Branch               : 
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
09-21 10:27:43.881 13962 13989 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-21 10:27:43.888 13962 13989 I AdrenoGLES-0: PFP: 0x016dc094, ME: 0x00000000
09-21 10:27:43.897 13962 13989 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-21 10:27:43.977 13962 13973 I zionhuang.musi: JIT allocated 54KB for compiled code of void w.n.f(int, int, long)
09-21 10:27:43.977 13962 13973 I zionhuang.musi: Compiler allocated 4717KB to compile void w.n.f(int, int, long)
09-21 10:27:54.271 13962 13962 W MirrorManager: this model don't Support
09-21 10:27:54.381 13962 13989 E FrameEvents: updateAcquireFence: Did not find frame.
09-21 10:28:09.098 13962 13962 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10377; state: ENABLED
09-21 10:28:11.834 13962 13989 D OpenGLRenderer: endAllActiveAnimators on 0xb4000072b4fea400 (q0$c) with handle 0xb4000072d5bb79a0
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:11.918 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:12.544 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:12.544 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:12.692 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:12.692 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:12.796 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:12.860 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:12.860 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.009 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.052 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.052 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:13.190 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.141 13962 13989 D OpenGLRenderer: endAllActiveAnimators on 0xb40000734873a000 (q0$c) with handle 0xb4000072d543ac40
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:30.252 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.472 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.549 13962 13962 W Choreographer: Frame time is 0.037291 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
09-21 10:28:32.597 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.676 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.724 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.801 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.854 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.932 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:32.932 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.081 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.119 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.198 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.248 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.330 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.380 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.444 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.514 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.591 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.646 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.711 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.793 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.793 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.897 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:33.897 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.029 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.104 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.104 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.229 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.292 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.372 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.372 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.490 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.575 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.576 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.691 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.754 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.829 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.880 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:34.959 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:35.007 13962 13962 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
09-21 10:28:51.749 13962 13989 D OpenGLRenderer: endAllActiveAnimators on 0xb4000072b4e43c00 (q0$c) with handle 0xb4000072d564df20
--------- beginning of crash
09-21 10:28:52.028 13962 14025 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-10
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Process: com.zionhuang.music, PID: 13962
09-21 10:28:52.028 13962 14025 E AndroidRuntime: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at bb.a.d(Unknown Source:20)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at d9.b.a(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at d9.b$a.u(Unknown Source:12)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at y9.a.p(Unknown Source:8)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at na.o0.run(Unknown Source:86)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at ta.a$a.run(SourceFile:9)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	Suppressed: na.m0: [y1{Cancelling}@d5ebf9c, Dispatchers.Default]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at androidx.fragment.app.w.t(Unknown Source:10)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.t(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at com.zionhuang.innertube.models.response.GetQueueResponse$a.e(SourceFile:3)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 6 more
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at androidx.fragment.app.w.t(Unknown Source:10)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.t(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at ab.p.k(SourceFile:1)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at ab.a.j(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at ab.a.e(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 11 more
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at androidx.fragment.app.w.t(Unknown Source:10)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.t(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at com.zionhuang.innertube.models.response.GetQueueResponse$QueueData$a.e(SourceFile:3)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 18 more
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at androidx.fragment.app.w.X(Unknown Source:27)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at com.zionhuang.innertube.models.PlaylistPanelRenderer$Content$a.e(SourceFile:3)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 23 more
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at androidx.fragment.app.w.t(Unknown Source:10)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.t(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at com.zionhuang.innertube.models.PlaylistPanelVideoRenderer$a.e(SourceFile:3)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 27 more
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0] at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at androidx.fragment.app.w.t(Unknown Source:10)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.t(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at com.zionhuang.innertube.models.Thumbnails$a.e(SourceFile:3)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 32 more
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing at path: $.queueDatas[116].content.playlistPanelVideoRenderer.thumbnail.thumbnails[0]
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:45)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at androidx.fragment.app.w.t(Unknown Source:10)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.t(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at ab.p.k(SourceFile:1)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at ab.a.j(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at ab.a.e(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 37 more
09-21 10:28:52.028 13962 14025 E AndroidRuntime: Caused by: xa.d: Fields [width, height] are required for type with serial name 'com.zionhuang.innertube.models.Thumbnail', but they were missing
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.E(SourceFile:4)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at com.zionhuang.innertube.models.Thumbnail.<init>(SourceFile:2)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at com.zionhuang.innertube.models.Thumbnail$a.e(SourceFile:3)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at j9.f.i(SourceFile:17)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	at cb.u.D(Unknown Source:5)
09-21 10:28:52.028 13962 14025 E AndroidRuntime: 	... 44 more
09-21 10:28:52.033 13962 14025 D OOMEventManagerFK: checkEventAndDumpForJE: 0
```

### Music version

0.4

### Android version

MIUI 13/Android 12

**Comment by airon90** [comment] 2022-09-21 08:33
In log I tried fetching 10 songs and it worked. Then I tried fetching 50 songs and it worked. I tried fetching 150 songs and it crashed

**Comment by z-huang** [comment] 2022-09-21 08:51
The cause is same as #191 and is fixed in `dev` branch.

**Closed by z-huang** 2022-09-21 08:51 UTC
Labels: bug
