### ISSUE TITLE
Error code:400 on app open

### ISSUE THREAD

**Issue by ishanveersg** [z-huang/music#310] opened 2022-10-16 00:23 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open the app

### Expected behavior

App should function normally

### Actual behavior

Error code 400 (Check the screenshot)

### Screenshots/Screen recordings

![error](https://user-images.githubusercontent.com/45516995/196012185-a511521a-3ac2-457d-b96a-a47ed8484558.png)

### Music version

0.4.1

### Android version

Android 13

**Comment by z-huang** [comment] 2022-10-16 00:48
Duplicate of #269

**Closed** 2022-10-16 00:48 UTC
Labels: bug, duplicate
