### ISSUE TITLE
Autosync playlists

### ISSUE THREAD

**Issue by siggi1984** [z-huang/music#1325] opened 2024-08-07 14:01 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add an option to sync playlists imported from YouTube automatically whenever you open the playlist.

### Why do you want this feature?

X

**Comment by z-huang** [comment] 2024-08-07 15:14
Duplicate of #990

**Closed as not planned by z-huang** 2024-08-07 15:14 UTC
Labels: enhancement
