### ISSUE TITLE
Crossfade music

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#155] opened 2022-08-19 22:06 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Crossfade music even if it only works for downloads.

### Why do you want this feature?

Like that the next song starts whiles the last is finishing.

### Additional information

In settings to be able to change the timer for the crossfade to start and a toggle for on or off to.

**Comment by z-huang** [comment] 2022-08-20 01:18
Duplicate of #54

**Closed** 2022-08-20 01:18 UTC
Labels: enhancement

**Comment by owencz1998** [comment] 2022-08-20 05:16
What the I tried looking for it just to naked sure I haven't done one before but couldn't find it my bad 😅
