### ISSUE TITLE
Playlist Photo

### ISSUE THREAD

**Issue by Fan-Bob** [z-huang/music#1290] opened 2024-06-15 12:49 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

add playlist Customize playlist images

### Why do you want this feature?

add photo

### Additional information

photo

**Comment by z-huang** [comment] 2024-08-04 13:10
Duplicate of #1114

**Closed as not planned by z-huang** 2024-08-04 13:10 UTC
Labels: enhancement
