### ISSUE TITLE
SD Card Local Storage

### ISSUE THREAD

**Issue by Roxo7777** [z-huang/music#1405] opened 2024-08-17 07:48 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Additional in Storage the option "local SD" to where the offline songs would be.

For those who have already downloaded a lot of songs to have to redownload, add another option to relocate (move) the songs already downloaded to the SD card, as in the Seal downloader application, or other music players.

### Why do you want this feature?

So as not to waste my cell phone storage.

**Comment by z-huang** [comment] 2024-08-17 10:09
If you want to migrate downloaded songs to a new phone, it's not possible. As you can see (if you're rooted), the downloaded files are named randomly. ExoPlayer maintains a database to map each song id to the downloaded files. However, this database isn't contained in the backup. So, even if you can set download location, without the database, these files cannot be recognized and played. You may ask: why not put exoplayer database into the backup? Because we don't know whether the downloaded file will stay when migrating to another phone.

If you're just asking for changing download location, duplicate of #1220.

**Closed as not planned by z-huang** 2024-08-17 10:09 UTC
Labels: enhancement
