### ISSUE TITLE
don't load new songs in principal screen.

### ISSUE THREAD

**Issue by 0uros** [z-huang/music#300] opened 2022-10-14 20:39 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open the app
slide down

### Expected behavior

See more recommended songs

### Actual behavior

Just I can't see more than that.

### Screenshots/Screen recordings

![Screenshot_20221014-173741_Music](https://user-images.githubusercontent.com/67289586/195939276-91add7b6-423b-462a-b2ae-6df0e3c4520c.png)

### Logs

java.lang.NullPointerException
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:25)
	at z6.g.b(SourceFile:4)
	at z6.g$c.t(Unknown Source:12)
	at u9.a.n(Unknown Source:8)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at ka.p0.run(Unknown Source:86)
	at pa.j.run(Unknown Source:12)
	at qa.j.run(Unknown Source:2)
	at qa.a$a.run(SourceFile:9)

### Music version

0.4.1

### Android version

Android 13

### Additional information

Anything to say.

**Comment by z-huang** [comment] 2022-10-15 04:50
Duplicate of #290

**Comment by z-huang** [comment] 2022-10-15 04:50
Use debug version if you don't want to wait for a new release.

**Closed** 2022-10-15 04:50 UTC
Labels: bug, duplicate
