### ISSUE TITLE
Add Feature by another free program

### ISSUE THREAD

**Issue by Fan-Bob** [z-huang/music#1282] opened 2024-06-05 16:34 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Youtube Music playlists should be added to the Innertune playlists and Innertune playlists should be added to YouTube Music playlists. If the name of the YouTube Music playlist matches the name of the Innertune playlist, they should be merged. YouTube Music playlist "Your Likes" should be merged with the "Favorites" playlist of Innertune. The synchronisation feature should be optional, so users can turn the synchronisation off, or turn the synchronisation on only on "Your Likes" playlist etc.

### Why do you want this feature?

The login support is pretty limited, allowing only to listen to the playlists saved on your YouTube account. By adding the synchronisation it would be more convenient to the user to listen to the same playlist on PC in browser and on the phone in Innertune

### Additional information

Really hope that we can accomplish this through this website.
This website provides unlimited YouTube music playlist export and import functions. The only limit is that up to 500 tasks can be performed at the same time. Free account

**Comment by Fan-Bob** [comment] 2024-06-05 16:38
https://www.tunemymusic.com/

**Comment by z-huang** [comment] 2024-08-04 12:09
Duplicate of #990

**Closed as not planned by z-huang** 2024-08-04 12:09 UTC
Labels: enhancement
