### ISSUE TITLE
Can Not Play Albums unless on the Library And Cannot Add Albums to The Library 

### ISSUE THREAD

**Issue by eddcm123** [z-huang/music#1307] opened 2024-07-19 15:26 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Try to Open an Album Not on your library 
Try to Add and Album to your Library 
It Doesn't Work 

### Expected behavior

Albums should open 
I should be able to add an album to my library 

### Actual behavior

It doesn't do it

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/5bc680f1-b912-47e2-a769-ba5073002bd2

### Logs

Adb logcat

https://github.com/user-attachments/assets/e8196f2e-0817-4f4a-af55-67bc54862e4c

Idk how help

### InnerTune version

0.5.3

### Android version

13

### Additional information

Pixel 7a

**Comment by z-huang** [comment] 2024-08-04 07:59
Duplicate of #1295

**Closed as not planned by z-huang** 2024-08-04 07:59 UTC
Labels: bug
