### ISSUE TITLE
Warning when adding duplicate songs to a playlist

### ISSUE THREAD

**Issue by balaraz** [z-huang/music#1188] opened 2024-01-02 13:21 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

* Check if the song is already in this playlist. If the song is already in the playlist, a pop-up menu should appear with a warning and buttons to `Add` and `Cancel` it.
* You can also add an item to the settings whether you want to check for a song in the playlist.

### Why do you want this feature?

It is not always possible to remember whether you have already added this song or not

**Comment by z-huang** [comment] 2024-01-06 04:04
Duplicate of #156

**Closed as not planned by z-huang** 2024-01-06 04:04 UTC
Labels: enhancement
