### ISSUE TITLE
Importing playlist

### ISSUE THREAD

**Issue by owencz1998** [z-huang/music#181] opened 2022-09-16 05:21 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Find your yt music playlist
Import

### Expected behavior

Import and save the songs onto the app

### Actual behavior

Click import and the app crashes with a error on playlist

### Screenshots/Screen recordings

![Screenshot_20220916_061914_Music Debug](https://user-images.githubusercontent.com/96526481/190562366-7762ec89-64d6-45ad-a838-d24d02aa536e.jpg)

### Music version

0.4.0

### Android version

12

**Comment by z-huang** [comment] 2022-09-16 05:48
Is this a duplicate of #179?

**Comment by owencz1998** [comment] 2022-09-16 06:56
I can search the playlist and it does come up but importing doesn't work and the songs in the library don't show up

**Comment by z-huang** [comment] 2022-09-16 07:36
Fixed.

**Closed by z-huang** 2022-09-16 07:36 UTC
Labels: bug
