### ISSUE TITLE
Remove more songs from the queue at the same time

### ISSUE THREAD

**Issue by attilafekete73** [z-huang/music#1129] opened 2023-10-30 22:11 UTC
### Checklist

- [x] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

If you press a song in the queue for approx. 3 secs, you should be able to select it and then by some quick presses you could select more songs and then you could delete them from the queue at the same time

### Why do you want this feature?

It would make the app more efficient

**Comment by z-huang** [comment] 2024-01-10 09:05
Duplicate of #695

**Closed as not planned by z-huang** 2024-01-10 09:05 UTC
Labels: duplicate, enhancement
