### ISSUE TITLE
Expanded album view is blank for any artist

### ISSUE THREAD

**Issue by AnonRS3** [z-huang/music#1124] opened 2023-10-24 04:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to any artist page
2. Click the arrow to see all albums
3. It is loading forever / blank

### Expected behavior

It should show the albums. 

### Actual behavior

It just stays blank and never loads. 

### Screenshots/Screen recordings

![Screenshot_20231023-235908](https://github.com/z-huang/InnerTune/assets/54009117/db72d0df-e13b-43b6-8169-2d12ebe56cd8)

### Logs

[24-10_00-02-01.log](https://github.com/z-huang/InnerTune/files/13110673/24-10_00-02-01.log)

### InnerTune version

0.5.3

### Android version

Android 14

### Additional information

The latest 3-4 debug apps just crash immediately for me and show an error as a notification. I can open a separate issue for that if you want, just let me know. 

Issue #1092 seems that people are experiencing the same problem, but I provided logs here, so I recommend closing that issue in favor of this one.

**Comment by SiddhantRakh** [comment] 2023-10-25 07:34
Same here.

**Comment by z-huang** [comment] 2023-10-28 00:32
Duplicate of #1048

**Closed as not planned by z-huang** 2023-10-28 00:32 UTC
Labels: bug
