### ISSUE TITLE
App doesn’t work properly 

### ISSUE THREAD

**Issue by pdimu** [z-huang/music#1308] opened 2024-07-20 14:06 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Albums, community playlists, artists, etc.
All these are resolved in the Malopieds fork.

### Expected behavior

They should be showing the songs and all others

### Actual behavior

There’s nothing there and you can’t play albums

### Screenshots/Screen recordings

Not now 

### Logs

Not now

### InnerTune version

0.5.3

### Android version

Android 12

### Additional information

Why not import at least the solved parts of the app? Ok, the fork is really really good, but innertune is still worth it
Please @z-huang cone back and solve these issues up

**Comment by z-huang** [comment] 2024-08-04 07:55
Duplicate of #1295.

Sorry, I'm busy these days. 🥲  I'll merge the fix soon.

**Closed as not planned by z-huang** 2024-08-04 07:55 UTC
Labels: bug
