### ISSUE TITLE
Sync app playlist with YouTube playlist.

### ISSUE THREAD

**Issue by Francis3and7** [z-huang/music#1185] opened 2023-12-29 03:50 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I was very happy to see that the app allowed me to copy my YouTube playlists. But I realized that the changes I make in the app are not made on YouTube. I would like to see a feature or setting added for this.

### Why do you want this feature?

I use the app's playlists on Android. However, I still use YouTube playlists on other devices, and it ends up being tiring to make changes manually so that both playlists are identical.

**Comment by HENRYMARTIN5** [comment] 2023-12-30 14:05
I'd also love to see this added - I came here specifically to make this suggestion and am glad someone else has already had the same idea.

**Comment by z-huang** [comment] 2024-01-06 04:06
Duplicate of #990

**Closed as not planned by z-huang** 2024-01-06 04:06 UTC
Labels: duplicate, enhancement
