### ISSUE TITLE
Album not opening 

### ISSUE THREAD

**Issue by Chickenshrimps** [z-huang/music#1303] opened 2024-07-06 02:51 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to the album section
Click on any album playlist songs 

### Expected behavior

It opens and starts playing 

### Actual behavior

List empty error code shows 

### Screenshots/Screen recordings

![Screenshot_20240706_081939](https://github.com/z-huang/InnerTune/assets/108865702/22d44613-5bc9-4e5e-99f8-3402bad265ae)

### Logs

java.util.NoSuchElementException: List is empty.
	at ra.q.H0(Unknown Source:21)
	at x7.h.a(SourceFile:235)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### InnerTune version

0.4.4

### Android version

Android 12

**Comment by Farimah3** [comment] 2024-07-06 16:56
it's not opening any pages

**Comment by Chickenshrimps** [comment] 2024-07-07 07:44
Yes not even my own playlist isn't opening

**Comment by airon90** [comment] 2024-07-09 09:45
I suppose it is a duplicate of #1295

**Comment by Chickenshrimps** [comment] 2024-07-10 03:39
> I suppose it is a duplicate of #1295

What do you mean ? Can't the problem be fixed

**Comment by phantomwhale** [comment] 2024-07-15 00:09
The fork at https://github.com/Malopieds/InnerTune/releases has version 0.5.8 which fixed playlist / album loading issues for me.

**Comment by z-huang** [comment] 2024-08-04 07:51
Duplicate of #1295

**Closed as not planned by z-huang** 2024-08-04 07:51 UTC
Labels: bug
