### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Ramhoe** [z-huang/music#298] opened 2022-10-14 10:09 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Bottom of the start page

### Expected behavior

It's supposed to load more music

### Actual behavior

It doesn't 

### Logs

java.lang.NullPointerException
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:25)
	at z6.g.b(SourceFile:4)
	at z6.g$c.t(Unknown Source:12)
	at u9.a.n(Unknown Source:8)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at f9.h.f(SourceFile:5)
	at f9.h.d(SourceFile:2)
	at f9.h$a.n(SourceFile:5)
	at u9.a.n(Unknown Source:31)
	at ka.p0.run(Unknown Source:86)
	at pa.j.run(Unknown Source:12)
	at qa.j.run(Unknown Source:2)
	at qa.a$a.run(SourceFile:9)

### Music version

0.4.1

### Android version

11

**Comment by z-huang** [comment] 2022-10-14 10:45
Duplicate of #290

**Closed** 2022-10-14 10:45 UTC
Labels: bug, duplicate
