### ISSUE TITLE
Backup filename doesn't work with restore

### ISSUE THREAD

**Issue by phantomwhale** [z-huang/music#1202] opened 2024-01-12 10:39 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Backup your data to a file using default name
Try and restore the file - file can't be selected

### Expected behavior

You should be able to restore the backup file without altering its name

### Actual behavior

Restore leaves the *.backup file greyed out. Renaming it to remove the .backup extension allows it to be selected

### Logs

No logs provided

### InnerTune version

0.5.3

### Android version

Android 14

**Comment by DeadSecTr** [comment] 2024-01-14 13:25
Cant confirm that...it works for me

**Comment by Malopieds** [comment] 2024-01-18 21:46
If you could provide the backup file, it would help a lot identifying your issue

**Comment by 0x263b** [comment] 2024-01-24 04:02
Same issue here. Uploaded a backup to Google Drive on one phone and downloaded on another. Wouldn't allow me to select the file on the new phone. Transferring the backup file over USB worked however.

**Comment by Malopieds** [comment] 2024-01-24 06:54
@phantomwhale @0x263b I can't reproduce it, you either send a reproductible minimal backup or close this as non reproducible.

**Comment by 0x263b** [comment] 2024-01-24 07:21
Here's a backup I just made https://drive.google.com/file/d/10BSOyUBcrrWQ7MRo1LQ9vGkVOSsPFAt9/view?usp=drive_link

Steps to reproduce:

1. create backup
2. file should be selectable to restore from
3. upload backup to Google Drive
4. delete local backup file
5. download backup from Google Drive
6. downloaded backup file can not be selected

**Comment by Malopieds** [comment] 2024-01-24 07:35
> Here's a backup I just made https://drive.google.com/file/d/10BSOyUBcrrWQ7MRo1LQ9vGkVOSsPFAt9/view?usp=drive_link

I just downloaded it from your link.
![Screenshot_20240124-083437_1.png](https://github.com/z-huang/InnerTune/assets/74783202/f9e379d6-e15c-4b5a-a5f0-b464a2196c57)

It isn't grayed out for me.

**Comment by z-huang** [comment] 2024-08-04 12:52
I think it's depend on your Android OS.

**Closed as not planned by z-huang** 2024-08-04 12:52 UTC
Labels: bug
