### ISSUE TITLE
Add Google Assistant support

### ISSUE THREAD

**Issue by yqyu-uyqu** [z-huang/music#1135] opened 2023-11-06 19:40 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add support to ask Google to play music on InnerTune.

### Why do you want this feature?

I would like this so that I can more conveniently use InnerTune with my headphones, when I cannot use my phone.

**Comment by z-huang** [comment] 2024-01-10 08:59
Duplicate of #111

**Closed as not planned by z-huang** 2024-01-10 08:59 UTC
Labels: enhancement
