### ISSUE TITLE
Round corners on the artwork image

### ISSUE THREAD

**Issue by Radical4ever** [z-huang/music#229] opened 2022-09-25 14:19 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Use of rounded corners (like retro music player or youtube music now playing screen)

![Screenshot_20220925_111614](https://user-images.githubusercontent.com/83252104/192148442-cdd0d7dc-53e9-463a-adfa-15957cf00c9d.png)

### Why do you want this feature?

Bc it looks good and makes it look modern

### Additional information

Even more awesome it would be to choose the corner radius (to make it look more like samsung music)

**Comment by z-huang** [comment] 2022-09-26 03:31
Duplicate of #84
I'll do it along with the bottom sheet player redesign.

**Closed** 2022-09-26 03:31 UTC
Labels: duplicate, enhancement
