### ISSUE TITLE
Region change doesn't update the songs on home page

### ISSUE THREAD

**Issue by YouSummoner** [z-huang/music#231] opened 2022-09-25 15:33 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to settings
2. Go to content
3. Change default content country 

### Expected behavior

The recommended songs on the app's home page should be updated according to the content country selected.

### Actual behavior

The recommendations stay according to the country in which the app was first opened.

### Screenshots/Screen recordings

![Screenshot_20220925-210001_Music](https://user-images.githubusercontent.com/107224555/192151777-ed374b5c-30ce-42bc-8917-1080816a561d.png)
![Screenshot_20220925-205953_Music](https://user-images.githubusercontent.com/107224555/192151783-0e074a4a-0b43-4270-829e-7dccdb506ec1.png)

### Music version

0.4.1

### Android version

Android 12.1

**Comment by z-huang** [comment] 2022-09-25 15:34
Duplicate of #202

**Closed by z-huang** 2022-09-25 15:34 UTC
Labels: bug
