### ISSUE TITLE
SponsorBlock API integration

### ISSUE THREAD

**Issue by ann-dvlpr** [z-huang/music#1224] opened 2024-01-24 08:43 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

SponsBlock API Allows us to block useless segments set by community (e.g. non-music parts like silence, or reminder to subscribe at the end of song, or even at the start.)

### Why do you want this feature?

If the API will be integrated the music listening process will be more interesting and without waitings song to start playing it's actual part.

### Additional information

Provide an setting category for it and it's setting. You can refer to YouTube Revanced eXtended (music).

**Comment by z-huang** [comment] 2024-01-24 08:44
Duplicate of #495

**Comment by ann-dvlpr** [comment] 2024-01-24 08:45
Oh, I'm sorry. While search thru "SponsorBlock" I couldn't find any issues with it, so that's why I created issue

**Closed as not planned by z-huang** 2024-01-24 08:44 UTC
Labels: duplicate, enhancement
