### ISSUE TITLE
New song not play 

### ISSUE THREAD

**Issue by shobhagyabehera** [z-huang/music#1674] opened 2024-10-25 15:14 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/952d58e8-cb34-437e-a9a8-b0fb108ba063)

### Why do you want this feature?

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/0916b80f-eefa-4777-8f54-dfc430c6d0b9)

### Additional information

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/0b4586e5-5502-4577-8db3-1e0e8564b66e)

**Comment by ganairm** [comment] 2024-10-25 16:13
just go to settings -> content -> login. then it'll be fine

**Comment by gechoto** [comment] 2024-10-25 21:46
Duplicate of:
https://github.com/z-huang/InnerTune/issues/1673
https://github.com/z-huang/InnerTune/issues/1660
https://github.com/z-huang/InnerTune/issues/1657
https://github.com/z-huang/InnerTune/issues/1654
https://github.com/z-huang/InnerTune/issues/1653
https://github.com/z-huang/InnerTune/issues/1645
https://github.com/z-huang/InnerTune/issues/1632
https://github.com/z-huang/InnerTune/issues/1614

Please close this one.

**Closed as not planned** 2024-10-26 16:36 UTC
Labels: enhancement
