### ISSUE TITLE
Unable to view albums

### ISSUE THREAD

**Issue by Angy-Kitty** [z-huang/music#1092] opened 2023-09-23 17:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to any artist's page
2. Click the arrow next to the albums heading

### Expected behavior

The artist's albums should be displayed 

### Actual behavior

InnerTune is stuck loading the albums page

### Screenshots/Screen recordings

![IMG_20230922_175558](https://github.com/z-huang/InnerTune/assets/123874131/15bf846d-a28c-403f-9d30-1772596530f0)

### Logs

I don't know how to log app activity 

### InnerTune version

0.5.3 Foss

### Android version

Android 10 QKQ1.190910.002

### Additional information

The latest DEBUG version of InnerTune does not work on my device (Xiaomi Mi 8 Lite)

**Comment by baruchin** [comment] 2023-09-24 22:01
I'm experiencing the same bug on a Poco F3

**Comment by Sofa44** [comment] 2023-09-27 01:24
I have the same with both my Pixel 3a, and Samsung A12.

**Comment by senolfndk** [comment] 2023-09-27 14:38
dear developer is imitating you https://play.google.com/store/apps/details?id=com.voxify&ref=producthunt

**Comment by github-user93** [comment] 2023-09-29 10:15
same also happens for the singles tab for me. redmi note 7 pro, miui 12.5.1, android 10

**Comment by candroid-man** [comment] 2023-09-30 17:36
Same here on the Pixel 6 Pro

**Comment by z-huang** [comment] 2023-10-28 00:32
Duplicate of #1048

**Closed as not planned** 2023-10-28 00:33 UTC
Labels: bug, can't reproduce

**Comment by senolfndk** [comment] 2023-10-29 07:38
Same problem 😒 Samsung A21s Android 12

**Comment by rpierrot** [comment] 2024-01-17 21:36
Same on Poco F3

**Comment by z-huang** [comment] 2024-01-18 07:20
Please provide logs, so I can provide further assistant.

**Comment by ITSVENOV** [comment] 2024-07-14 23:31
I am facing the same issue what did you do to fix it? Plz help

**Comment by mryusufcan** [comment] 2024-08-01 19:15
help please poco F5
