### ISSUE TITLE
Spotify Lyrics API as a source for Lyrics

### ISSUE THREAD

**Issue by SiddhantRakh** [z-huang/music#1193] opened 2024-01-04 11:55 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Instead of using the current lyrics provider integration i think the Spotify Lyrics API is a better source having access to lyrics for many more songs especially which are non-English and regional. 

### Why do you want this feature?

This will improve the lyrics experience and let the users fully enjoy the Lyrics UI of Innertune which is the best without worrying for the availability of lyrics. 

### Additional information

Some other players have already started using Spotify Lyrics API for similar purposes.

**Comment by z-huang** [comment] 2024-01-07 13:01
Duplicate of #1002

**Closed as not planned by z-huang** 2024-01-07 13:01 UTC
Labels: duplicate, enhancement
