### ISSUE TITLE
Option to change the default downloads location

### ISSUE THREAD

**Issue by Eliceoxd** [z-huang/music#1350] opened 2024-08-11 05:28 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to have the option to change the place where the app stores the downloads so I can change it and It would be nice to have the possibility to use the sd card as a storage route 

### Why do you want this feature?

My phone is a bit old and I currently use a 256gb sd card to compensate for its low base storage space, so it would be nice to have the option available to download more music and play it offline

**Comment by bazilbycom** [comment] 2024-08-13 13:24
Yes. We need m4a files so that we can use third party players as well.

**Comment by z-huang** [comment] 2024-08-13 16:01
> Yes. We need m4a files so that we can use third party players as well.

If you want to use other players, you just need a YouTube downloader app, such as NewPipe. Even if the app supports changing download location, the file will be in `.exo` format, which can not be directly played.

**Comment by z-huang** [comment] 2024-08-14 04:33
Duplicate of #1220

**Closed as not planned by z-huang** 2024-08-14 04:33 UTC
Labels: enhancement
