### ISSUE TITLE
New music notifications button

### ISSUE THREAD

**Issue by Roxo7777** [z-huang/music#1458] opened 2024-08-26 04:18 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There could be notifications from the app itself, and a button where you would see notifications of new albums or singles from those I follow, just like in YouTube Music.

### Why do you want this feature?

Not to depend on YouTube Music to see if my singer who follows has released something new.

### Additional information

You could copy the simplicity of Spotify's notification panel, but I think YouTube Music's is visually beautiful.

**Comment by z-huang** [comment] 2024-08-28 03:32
Duplicate of #1447.

**Closed as not planned by z-huang** 2024-08-28 03:32 UTC
Labels: enhancement
