### ISSUE TITLE
Typo (Settings `String`)

### ISSUE THREAD

**Issue by VedxP** [z-huang/music#302] opened 2022-10-15 04:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open Settings
2. There's an option named as `Gerenal`

### Expected behavior

It should be `General`

### Actual behavior

But, it's written as `Gerenal` instead of `General`.

### Screenshots/Screen recordings

![Screenshot_20221015-102328~2](https://user-images.githubusercontent.com/87353286/195969522-1cb1a123-059c-4ec0-8a50-5665ebf71e7b.png)
![Screenshot_20221015-102332~2](https://user-images.githubusercontent.com/87353286/195969542-4f4de7e4-753c-495d-8a6d-da14262a2649.png)

### Music version

0.4.1

### Android version

Android 12

**Comment by KillerEnigma** [comment] 2022-10-15 05:52
I want to pick the issue

**Comment by z-huang** [comment] 2022-10-15 05:52
Duplicate of #240

**Closed** 2022-10-15 05:52 UTC
Labels: bug, duplicate
