### ISSUE TITLE
Clicking the three dots on a playlist in "Explore" doesn't do anything

### ISSUE THREAD

**Issue by KakarottoCake** [z-huang/music#132] opened 2022-07-10 01:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to "Explore"
Search for a playlist
Press on the 3 dots next to the playlist

### Expected behavior

A drop-down menu that displays options including "download" or "add" would show 

### Actual behavior

Literally nothing happens

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/61133727/178127819-e7b07eb0-37a7-4f54-83c8-67c330d55803.mp4

### Music version

0.3.1

### Android version

Android 12

**Comment by z-huang** [comment] 2022-07-10 03:58
Duplicate of #28.

**Closed by z-huang** 2022-07-10 03:58 UTC
Labels: bug
