### ISSUE TITLE
New song not play 

### ISSUE THREAD

**Issue by shobhagyabehera** [z-huang/music#1673] opened 2024-10-25 15:11 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/674aac47-ee2f-4d75-97e9-8d74bb0a5c16)
Not play new song 

### Expected behavior

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/b87f12b5-8a4e-4daf-b070-940bc6bc192c)

### Actual behavior

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/f8615cce-1366-4f66-a216-5d30782b2126)

### Screenshots/Screen recordings

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/6dc9a117-e445-43af-b5c9-0bd25b8270fb)

### Logs

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/a010f360-83c9-41e4-b32e-f23c32a88527)

### InnerTune version

0.5.7

### Android version

Android 13

### Additional information

![Screenshot_20241025_203617](https://github.com/user-attachments/assets/c94aa28b-ba0d-456a-a7f3-3dbd8de28c59)

**Comment by shobhagyabehera** [comment] 2024-10-25 15:12
New song not play

**Comment by ganairm** [comment] 2024-10-25 16:14
login, the issue will be fixed

**Comment by Samarthsattani66** [comment] 2024-10-25 17:04
When it will be solved

**Comment by gechoto** [comment] 2024-10-25 21:37
Please try to avoid creating duplicates. There are a lot of bug reports about this exact problem already. No need to spam the developer, it only creates more work.
It would be better for everyone to comment on ONE issue instead of spreading comments all over the place.

Duplicate of:
https://github.com/z-huang/InnerTune/issues/1674
https://github.com/z-huang/InnerTune/issues/1666
https://github.com/z-huang/InnerTune/issues/1660
https://github.com/z-huang/InnerTune/issues/1657
https://github.com/z-huang/InnerTune/issues/1654
https://github.com/z-huang/InnerTune/issues/1653
https://github.com/z-huang/InnerTune/issues/1645
https://github.com/z-huang/InnerTune/issues/1632
https://github.com/z-huang/InnerTune/issues/1614

**Comment by gechoto** [comment] 2024-10-25 21:43
I just used the search function and this seems to be the first reported issue about it (correct me if I'm wrong):
https://github.com/z-huang/InnerTune/issues/1614

@shobhagyabehera 
It would be cool if you would close this one and instead comment on the other one. (Or at least one of the other ones, there are enough already.)

**Closed as not planned** 2024-10-26 16:36 UTC
Labels: bug
