### ISSUE TITLE
Show Error 

### ISSUE THREAD

**Issue by IamRoyals** [z-huang/music#1304] opened 2024-07-06 03:46 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### Expected behavior

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### Actual behavior

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### Screenshots/Screen recordings

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### Logs

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### InnerTune version

0.5.3

### Android version

Android 10

### Additional information

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

**Comment by phantomwhale** [comment] 2024-07-15 00:09
The fork at https://github.com/Malopieds/InnerTune/releases has version 0.5.8 which fixed playlist / album loading issues for me. The discussion on #1295 covers this bug.

I've moved over to that fork (which has active development; kudos to @Malopieds) and away from this release (which appears to be no longer working now; but kudos to @z-huang for all his work underpinning the new fork)

**Comment by z-huang** [comment] 2024-08-04 07:52
Duplicate of #1295

**Closed as not planned by z-huang** 2024-08-04 07:52 UTC
Labels: bug
