### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by senolfndk** [z-huang/music#70] opened 2022-06-01 04:29 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

![Screenshot_20220531-232626_Music](https://user-images.githubusercontent.com/52818836/171327126-9c05fee2-2dd6-4722-a45c-2153579bc650.jpg)

### Expected behavior

can you help me please

### Actual behavior

![Screenshot_20220601-063827_Lawnchair](https://user-images.githubusercontent.com/52818836/171327813-0da3778a-30e7-4e92-8dd9-da28a344e425.jpg)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/52818836/171326431-84cb2149-e875-4ac8-9a69-5341aebde254.mp4

### Logs

app crashes while searching

### Music version

0.3.0

### Android version

android 11

### Additional information

![Screenshot_20220601-063827_Lawnchair](https://user-images.githubusercontent.com/52818836/171326883-4751d54c-40a4-4d23-a99b-5496e304b70e.jpg)

**Comment by z-huang** [comment] 2022-06-01 05:00
I need logs so that I can know why the crash happens. 🙏

**Comment by airon90** [comment] 2022-06-01 07:26
@senolfndk Read here to find out how to create a log https://github.com/z-huang/music/issues/38#issuecomment-1109655418

**Comment by z-huang** [comment] 2022-06-09 07:13
Duplicate of #85.

**Closed by z-huang** 2022-06-09 07:13 UTC
Labels: bug
