### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by senolfndk** [z-huang/music#85] opened 2022-06-09 07:03 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

crashing

### Expected behavior

crashes while searching

### Actual behavior

crashes while searching

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/52818836/172785189-b5975f20-1907-47b8-8019-020dda2ab3b5.mp4

### Logs

crashes while searching

### Music version

0.3.1

### Android version

android 11

### Additional information

crashes while searching

**Comment by z-huang** [comment] 2022-06-09 07:12
I think this is a duplicate of #70. I need logs to know the root cause.

**Closed** 2022-06-17 19:16 UTC
Labels: bug
